services:
  frontend:
    container_name: chic-chat-frontend
    image: chic-chat-frontend
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_SERVER_PROTOCOL: http
        VITE_SERVER_HOST: chic-chat-backend
        VITE_SERVER_PORT: 8080
    ports:
      - 3000:3000
    networks:
      - chic-chat-networks

networks:
  chic-chat-networks:
    driver: bridge
